import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { BottomNavbar } from "@/components/layout/bottom-navbar";
import Silk from "@/components/Silk";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        figtree.variable,
      )}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed inset-0 -z-10 w-full h-[100lvh] overflow-hidden will-change-transform backface-hidden">
            <div className="absolute inset-0 w-full h-full">
              <Silk
                speed={5}
                scale={1}
                color="#5227FF"
                noiseIntensity={1.5}
                rotation={0}
              />
            </div>
          </div>
          {children}
          <BottomNavbar />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
