spring:
  application:
    name: demo
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/migration/dev # remove in production
    check-location: true
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

cloudinary:
  cloud_name: ${CLOUDINARY_NAME:}
  api_key: ${CLOUDINARY_API_KEY:}
  api_secret: ${CLOUDINARY_API_SECRET:}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:604800000} # falls back to 7 days if not set

server:
  port: 8080
