spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb # change "mydb" to your db name
    username: postgres # change to your username
    password: yourpassword # change to your password
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/migration/dev # Mock data seeder.
        # NOTE: This directory contains the mock data seeder script (R__*.sql).
        # When active, it will wipe and re-seed all users and events on application
        # startup or whenever the SQL file is modified.
    check-location: true
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

jwt:
  secret: your-very-secure-secret-key-at-least-256-bits-long
  expiration: 604800000 #   7 days

cloudinary:
  cloud_name: name # change to your cloud name
  api_key: key # change to your key
  api_secret: secret # change to your secret

server:
  port: 8080
